# Generated by Django 2.1.7 on 2019-02-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('Question', 'Question'), ('Event', 'Event'), ('News', 'News')], max_length=10),
        ),
    ]
